name: domain
description: Domain package for Alex Astudillo ERP
version: 0.0.1
# homepage:
# repository: 

environment:
  sdk: ">=2.17.1 <3.0.0"

# dependencies:

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1
